version: '3.7'
services:
  web:
    build:
      context: ./web
    ports:
      - 3000:3000
    environment:
      - REACT_APP_BASE_API_URL=http://macbook.local:4433
    volumes:
      - ./web:/web
  server:
    build:
      context: ./server
    ports:
      - 4433:4433
    volumes:
      - ./server:/server/
    links:
      - mongo
      - mariadb
    depends_on:
      - mongo
      - mariadb
    env_file:
      - ./server/dockerDev.env
  mongo:
    image: mongo
    volumes:
      - ./data/mongo:/data/db
    ports:
      - 27017:27017
    environment:
      - MONGO_DATA_DIR=/data/db
  mariadb:
    image: mariadb
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=classmate
      - MYSQL_DATABASE=iic_db_dev
